spring.application.name=EmailDemoApp  


                                                                                                                          spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.username=pavanikolavennu16@gmail.com
spring.mail.password=fqkm wqvk ikqo cpld

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true